version: "3.10"

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/bot
    command: python /bot/bot.py
    env_file:
      - .envrc
    environment:
      TERM: xterm-color