version: "3.10"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/newssite
    command: python /bot/bot.py
    env_file:
      - .env
    environment:
      TERM: xterm-color